packages/config/src/index.ts, packages/contracts/contracts/Unirep.sol, packages/contracts/test/Airdrop.test.ts, packages/contracts/test/Attesting.test.ts, packages/contracts/test/EventFilters.test.ts, packages/contracts/test/ReputationVerifier.test.ts, packages/core/cli/deploy.ts, packages/crypto/package.json, packages/crypto/src/identity.ts, yarn.lock
- `js-sha256` will cause error in frontend and it will be updated in [@zk-kit/identity](https://github.com/appliedzkp/zk-kit/pull/25)
=> Replace `js-sha256` in `ZkIdentity`

packages/circuits/test/identityCommitment.test.ts, packages/circuits/test/processAttestations.test.ts, packages/circuits/test/proveUserSignUp.test.ts, packages/circuits/test/startTransition.test.ts, packages/circuits/test/userStateTransition.test.ts, packages/circuits/test/utils.ts, packages/contracts/src/index.ts, packages/contracts/test/Attesting.test.ts, packages/contracts/test/EventSequencing.test.ts, packages/contracts/test/ReputationVerifier.test.ts, packages/contracts/test/UserSignUpVerifier.test.ts, packages/contracts/test/utils.ts, packages/core/cli/genEpochKeyAndProof.ts, packages/core/cli/genReputationProof.ts, packages/core/src/UnirepState.ts, packages/core/src/UserState.ts, packages/core/src/utils.ts, packages/core/test/UnirepState/reputationProofEvent.test.ts, packages/core/test/UserState/UserState.test.ts, packages/core/test/UserState/reputationProofEvent.test.ts, packages/core/test/utils.ts, packages/crypto/src/identity.ts
Refactor accessor functions in `ZkIdentity` for backward compatibility.
=> Crypto backward compat

packages/contracts/contracts/Unirep.sol, packages/contracts/contracts/interfaces/IVerifier.sol, packages/contracts/scripts/verifier_groth16_template.txt
Unirep.sol contains multidimensional array and it cannot be compiled by subgraph: https://github.com/graphprotocol/graph-cli/issues/342
Packing proofs is not really necessary and using single dimensional array can save gas when deploying
- Remove `unpackProof` function in `Unirep.sol`
- Save gas from 4251748 to 4079800 in deployment
-
=> Single dimensional array contract

packages/circuits/package.json, packages/contracts/package.json, packages/contracts/scripts/prepare.js, packages/crypto/package.json, yarn.lock
fix: contracts prepare script
Allows `yarn build` to be run in individual package directories. Fixes `yarn pre` script in contracts packages.
-
-
-
=> fix: add typescript as dev dep to allow build

packages/contracts/src/proof/BaseProof.ts
`BaseProof` is initialized with a `SnarkProof`.
`BaseProof` is initialized with `SnarkProof` or `BigNumberish[]`
=> Proof args

packages/core/src/Synchronizer.ts
Make the event loading a function so it can be overridden in subclasses.
=> chore: revert event loading in sync

packages/core/src/Synchronizer.ts
=> feat: waitForSync wait for target block

packages/subgraph/README.md
=> Documentation

packages/contracts/src/deploy.ts
Deploy script will spread all `_settings` arguments onto config.
=> fix: take all possible arguments in deploy script

packages/core/src/Synchronizer.ts, packages/core/src/UserState.ts, packages/core/src/schema.ts, packages/core/test/UserState/userStateTransitionEvent.test.ts
Improves sync performance by indexing frequently accessed fields.
=> db indexes

packages/core/cli/genReputationProof.ts, packages/core/src/UserState.ts, packages/core/test/UserState/UserState.test.ts, packages/core/test/synchronizer/synchronizer.test.ts
=> remove noncelist from rep proof creation

packages/core/src/Synchronizer.ts
Emit an event for every blockchain event processed. Used for calculating sync percentage in the frontend.
=> feat(core): emit event for each event

packages/circuits/circuits/sparseMerkleTree.circom
=> remove path index constraint when calculating using Num2Bits

packages/contracts/contracts/Hash.sol, packages/contracts/contracts/SparseMerkleTree.sol, packages/contracts/contracts/test/SparseMerkleTreeTest.sol, packages/contracts/package.json, packages/contracts/src/poseidon.ts, packages/contracts/test/SMT.ts, packages/crypto/src/SparseMerkleTree.ts
=> SMT solidity implementation

packages/core/src/UserState.ts
=> feat(core): specify epoch of epoch key proof

README.md, packages/circuits/package.json, packages/circuits/scripts/time.ts, packages/circuits/test/utils.ts, packages/contracts/README.md, packages/contracts/package.json, packages/core/package.json, packages/core/src/Synchronizer.ts, packages/core/src/UserState.ts, packages/crypto/package.json, packages/crypto/src/SparseMerkleTree.ts, packages/crypto/src/crypto.ts, packages/crypto/src/identity.ts, yarn.lock
=> V1.1 merge v1.0.1

packages/core/src/Synchronizer.ts
Fixes a bug when a hex string (e.g. contract address) is passed as an attester id.
=> fix(core): explicitly convert attester id to bigint

packages/contracts/contracts/Unirep.sol
=> Owed key bugfix

.circleci/config.yml, packages/contracts/README.md, packages/contracts/package.json, packages/contracts/worker.js, packages/contracts/wrangler.toml, yarn.lock
Closes #173 
Reduces CI execution time by 50% by only building/installing circom in the `build` step.
=> Coverage reports

packages/core/package.json, packages/core/src/Synchronizer.ts, packages/core/src/schema.ts, yarn.lock
See vimwitch/anondb#9
Memory database connector doesn't have support for compound primary keys. See vimwitch/anondb#11
=> Anondb memory connector

packages/core/src/Synchronizer.ts, packages/core/test/attestation.test.ts, packages/core/test/epochTree.test.ts, packages/core/test/stateTree.test.ts, packages/core/test/userState.test.ts, packages/core/test/userStateTransition.test.ts
Issue Number: Closes #158 
-
-
-
=> V2 core test

packages/contracts/contracts/Unirep.sol, packages/core/test/attestation.test.ts
=> fix(contracts): emit correct epoch

packages/core/src/Synchronizer.ts
=> fix(core): correct hash on attestation object

packages/contracts/scripts/prepare.js
=> fix(contracts): handle error in prepare script

packages/core/src/Synchronizer.ts, packages/core/src/UserState.ts
This proof doesn't require a user identity.
=> refactor(core): move genAggregateEpochKey proof to synchronizer

packages/circuits/circuits/proveReputation.circom, packages/circuits/test/proveReputation.test.ts
- `pos_rep - neg_rep >= min_rep` => `pos_rep >= neg_rep + min_rep`
-
-
=> fix(circuits): prove minRep

packages/docs/docs/circuits-api/network-prover.md, packages/docs/docs/testnet-deployment.md, packages/docs/docs/welcome.md, packages/docs/sidebars.js
=> docs: Add testnet info

packages/docs/docusaurus.config.js, packages/docs/src/components/HomepageFeatures/index.js, packages/docs/src/components/HomepageFeatures/styles.module.css, packages/docs/src/css/custom.css, packages/docs/src/pages/index.js, packages/docs/src/pages/index.module.css, packages/docs/static/img/description-image.svg
=> refactor(docs): new design colors, images, layout

packages/circuits/provers/defaultProver.ts, packages/circuits/src/index.ts, packages/contracts/deploy/deploy.ts, packages/docs/docs/circuits-api/prover.md
=> fix(circuits): make getVKey async in prover

README.md
- update documentation link: https://developer.unirep.io/
-
-
=> doc: update documentation link

packages/contracts/test/attestation.test.ts
=> fix(contracts): fix epoch key collisions in tests

packages/core/src/UserState.ts
=> fix(core): find epoch key and epoch

README.md
- update requirements in readme
-
-
=> doc: update requirements

packages/circuits/circuits/proveReputation.circom, packages/circuits/circuits/verifyEpochKey.circom
=> refactor(circuits): fewer constraints for nonce check

packages/core/src/Synchronizer.ts, packages/docs/docs/core-api/synchronizer.md
=> chore(core): remove getAttestations function

packages/core/src/UserState.ts, packages/docs/docs/core-api/synchronizer.md, packages/docs/docs/core-api/user-state.md
Make `getEpochKeys` synchronous and adjust the arguments to make it more useful.
=> Get epoch keys fix

packages/core/package.json, packages/core/src/Synchronizer.ts, packages/core/src/UserState.ts, packages/core/test/UserState/epochKeyProof.test.ts, packages/core/test/UserState/reputationProofEvent.test.ts, packages/core/test/UserState/userStateTransitionEvent.test.ts, packages/core/test/utils.ts
=> fix(core): attestation function take epoch

packages/contracts/test/attestation.test.ts, packages/contracts/test/attesterSignup.test.ts, packages/contracts/test/epoch.test.ts, packages/contracts/test/userSignup.test.ts, packages/contracts/test/userStateTransition.test.ts, packages/contracts/test/verifier.test.ts, packages/core/test/attestation.test.ts, packages/core/test/epochTree.test.ts, packages/core/test/stateTree.test.ts, packages/core/test/synchronizer.test.ts, packages/core/test/userSignup.test.ts, packages/core/test/userState.test.ts, packages/core/test/userStateTransition.test.ts
closes #191
closes #226 
- A snapshot can only be reverted once: https://hardhat.org/hardhat-network/docs/reference#evm_snapshot
- So I use `beforeEach` to record all new snapshots
=> Evm revert

packages/contracts/contracts/Unirep.sol, packages/contracts/test/accessors.test.ts, packages/docs/docs/contracts-api/unirep-sol.md
=> feat(contracts): attesterMemberCount function

packages/contracts/contracts/Unirep.sol
=> fix(contracts): bug in bit shift logic

packages/docs/docs/core-api/user-state.md
=> chore(docs): add revealNonce option to genEpochKeyProof docs

packages/docs/docs/protocol/nullifiers.md
Issue Number: closes #245 
- should we remove it in `2.0.0-alpha-2` and `2.0.0-alpha-3`? @vimwitch 
-
-
=> chore(docs): remove reputation nullifier section

packages/circuits/package.json
=> remove unuse script

packages/contracts/test/hashchain.test.ts
Issue Number: closes #248 
-
-
-
=> test(contracts): get `hashchainIndex` from contract

.gitmodules, .prettierignore, package.json, packages/circuits/circuits/aggregateEpochKeys.circom, packages/circuits/circuits/epochKeyLite.circom, packages/circuits/circuits/identityCommitment.circom, packages/circuits/circuits/incrementalMerkleTree.circom, packages/circuits/circuits/modulo.circom, packages/circuits/circuits/proveReputation.circom, packages/circuits/circuits/signup.circom, packages/circuits/circuits/sparseMerkleTree.circom, packages/circuits/circuits/updateSparseTree.circom, packages/circuits/circuits/userStateTransition.circom, packages/circuits/circuits/verifyEpochKey.circom, packages/circuits/package.json, yarn.lock
Submodule approach to circom dependencies. The idea is to not use javascript level packages for circom at all. Instead we manage at the git level and point to a specific commit at the circomlib public origin.
=> Circomlib submodule

packages/core/src/Reputation.ts, packages/core/src/UserState.ts, packages/core/test/UserState/userStateTransitionEvent.test.ts, packages/core/test/utils.ts
Issue Number: https://github.com/Unirep/Unirep-Social/issues/198
- Reputation should take `BigNumber` type input, or the graffiti will be overwritten because `0 !== BigNumber.from(0)`
=> [v1] Fix graffiti

.circleci/config.yml
=> chore(ci): use circom v2.1.2 pending #289

packages/docs/docs/contracts-api/errors.md, packages/docs/docs/protocol/epoch-key.md, packages/docs/docs/protocol/trees.md, packages/docs/docs/testnet-deployment.md
=> Fix: typos

packages/docs/versioned_docs/version-2.0.0-alpha-2/protocol/epoch-key.md, packages/docs/versioned_docs/version-2.0.0-alpha-2/protocol/trees.md, packages/docs/versioned_docs/version-2.0.0-alpha-3/protocol/epoch-key.md, packages/docs/versioned_docs/version-2.0.0-alpha-3/protocol/trees.md
=> fix(docs): fix typo

.circleci/config.yml
=> fix(ci): use cloudflare context for publishing contract coverage

packages/circuits/src/BuildOrderedTree.ts, packages/circuits/test/buildOrderedTree.test.ts, packages/contracts/contracts/Hash.sol, packages/contracts/deploy/deploy.ts, packages/contracts/deploy/poseidon.ts, packages/contracts/test/attestation.test.ts, packages/contracts/test/config.test.ts, packages/contracts/test/epoch.test.ts, packages/contracts/test/epochSealing.test.ts, packages/contracts/test/userStateTransition.test.ts, packages/contracts/test/verifier.test.ts, packages/core/src/Synchronizer.ts, packages/core/src/UserState.ts, packages/core/test/attestation.test.ts, packages/core/test/epochTree.test.ts, packages/core/test/stateTree.test.ts, packages/core/test/synchronizer.test.ts, packages/test/src/index.ts, packages/utils/src/crypto.ts
=> chore: remove unused import function

packages/circuits/circuits/userStateTransition.circom
=> fix(circuits): check to_epoch range in ust

packages/circuits/circuits/bigComparators.circom, packages/circuits/package.json, packages/circuits/scripts/circuits.mjs, packages/circuits/scripts/prepare.js, packages/circuits/test/bigComparators.test.ts
=> refactor(circuits): refactor big comparison component

packages/core/src/UserState.ts, packages/core/test/epochKeyLite.test.ts, packages/docs/docs/core-api/user-state.md
Issue Number: close #311 
-
-
-
=> Epoch key lite proof

packages/core/src/Synchronizer.ts, packages/core/src/schema.ts, packages/core/test/synchronizerAttesters.test.ts
=> Multi attester epoch fix

packages/circuits/src/BuildOrderedTree.ts, packages/circuits/test/buildOrderedTree.test.ts, packages/circuits/test/proveReputation.test.ts, packages/circuits/test/userStateTransition.test.ts, packages/contracts/deploy/deploy.ts, packages/contracts/test/config.test.ts, packages/contracts/test/epochSealing.test.ts, packages/contracts/test/userSignup.test.ts, packages/contracts/test/verifier.test.ts, packages/core/src/UserState.ts, packages/core/test/attestation.test.ts, packages/core/test/epochKeyProof.test.ts, packages/core/test/epochTree.test.ts, packages/core/test/reputationProof.test.ts, packages/core/test/stateTree.test.ts, packages/core/test/synchronizer.test.ts, packages/core/test/synchronizerAttesters.test.ts, packages/core/test/test.ts, packages/core/test/userSignup.test.ts, packages/core/test/userState.test.ts, packages/core/test/userStateTransition.test.ts, packages/core/test/utils.ts
=> chore: remove unused functions/variables

packages/docs/blog/2023-03-02-unirep-social.md
adding blogpost of lesson learn and why we sunset unirep.social
=> adding new post - sunsetting unirep.social

packages/contracts/deploy/deploy.ts
Fixes for contract deployments
=> Deploy fixes

packages/contracts/hardhat.config.ts, packages/core/src/UserState.ts, packages/core/test/attestation.test.ts, packages/core/test/epochKeyLite.test.ts, packages/core/test/stateTree.test.ts, packages/core/test/synchronizerAttesters.test.ts, packages/core/test/userStateTransition.test.ts
Issue Number: #349 
- Skip epoch that there is no nullifier or signup event
-
-
=> fix(core): user should not receive data if not transition to that epoch

packages/core/hardhat.config.ts
=> feat(core): update hardhat compiler

packages/contracts/contracts/libraries/Polysum.sol
=> fix(contracts): `vals` overflow in `Polysum.add()`

packages/circuits/circuits/buildOrderedTree.circom, packages/circuits/circuits/epochKeyLite.circom, packages/circuits/circuits/proveReputation.circom, packages/circuits/circuits/userStateTransition.circom
=> chore(circuits): optimize circuit constraints

packages/contracts/contracts/Unirep.sol
=> feat(contracts): use `calldata` in function input

.circleci/config.yml, packages/contracts/package.json, packages/core/package.json
Hardhat `evm_snapshot`/`evm_revert` [leak memory](https://github.com/NomicFoundation/hardhat/issues/868) over time. Running the test suite in parallel prevents the memory leak from becoming too bad.
=> fix(ci): run contracts tests in parallel when possible

packages/contracts/contracts/Unirep.sol
=> chore(contracts): revert with error

packages/circuits/circuits/incrementalMerkleTree.circom, packages/circuits/scripts/circuits.mjs, packages/circuits/test/incrementalMerkleTree.test.ts
=> fix(circuits): don't allow inclusion proof for 0 leaf

packages/core/src/UserState.ts
=> fix(core): get data nullifier logic

packages/utils/package.json, yarn.lock
=> fix(utils): bump randomf version

packages/circuits/test/bigComparators.test.ts, packages/circuits/test/preventDoubleAction.test.ts, packages/circuits/test/proveReputation.test.ts, packages/circuits/test/userStateTransition.test.ts, packages/circuits/test/utils.ts, packages/contracts/test/attestation.test.ts, packages/contracts/test/attestationMax.test.ts, packages/contracts/test/userStateTransition.test.ts, packages/core/src/UserState.ts, packages/core/test/userStateTransition.test.ts, packages/docs/docs/protocol/epoch-key.md, packages/docs/docs/utils-api/hashes.md, packages/utils/README.md, packages/utils/package.json, packages/utils/src/IncrementalMerkleTree.ts, packages/utils/src/SparseMerkleTree.ts, packages/utils/src/crypto.ts, packages/utils/test/SparseMerkleTree.test.ts, packages/utils/test/crypto.test.ts, yarn.lock
Instead of exporting `hash[1-16]` import directly from `poseidon-lite`. This is better for tree shaking and reducing bundle size.
=> chore: bump poseidon-lite to 0.1.1

packages/circuits/package.json, packages/circuits/src/BaseProof.ts, packages/circuits/src/EpochKeyLiteProof.ts, packages/circuits/src/EpochKeyProof.ts, packages/circuits/src/PreventDoubleActionProof.ts, packages/circuits/src/ReputationProof.ts, packages/circuits/src/SignupProof.ts, packages/circuits/src/UserStateTransitionProof.ts, packages/circuits/src/circuits.ts, packages/circuits/test/epochKeyLite.test.ts, packages/circuits/test/preventDoubleAction.test.ts, packages/circuits/test/userStateTransition.test.ts, packages/core/src/Synchronizer.ts, packages/docs/docs/circuits-api/base-proof.md, packages/docs/docs/circuits-api/network-prover.md, yarn.lock
=> refactor(circuits): switch BigNumberish -> bigint, remove ethers dep

packages/contracts/contracts/Unirep.sol
=> chore(contracts): remove unused openzeppelin imports

packages/circuits/config/index.ts, packages/circuits/scripts/circuits.mjs, packages/circuits/src/index.ts, packages/contracts/test/attestation.test.ts, packages/contracts/test/attestationMax.test.ts, packages/contracts/test/attesterSignup.test.ts, packages/contracts/test/config.test.ts, packages/contracts/test/epoch.test.ts, packages/contracts/test/userSignup.test.ts, packages/contracts/test/userStateTransition.test.ts, packages/contracts/test/verifier.test.ts, packages/test/src/index.ts
=> refactor(circuits): remove root level config folder

packages/utils/package.json, yarn.lock
Uses the new minor version of `poseidon-lite`. This version is MIT licensed and ~4x faster.
=> chore(utils): bump poseidon-lite

packages/contracts/contracts/Unirep.sol, packages/contracts/contracts/interfaces/IUnirep.sol, packages/contracts/contracts/libraries/LazyMerkleTree.sol, packages/contracts/contracts/libraries/ReusableMerkleTree.sol, packages/contracts/contracts/test/MerkleTreeTest.sol, packages/contracts/deploy/deploy.ts, packages/contracts/test/attestationMax.test.ts, packages/contracts/test/lazyMerkleTree.test.ts, packages/contracts/test/merkleTree.test.ts
=> feat(contracts): lazy merkle tree, reusable merkle tree tests

packages/contracts/package.json, yarn.lock
Decreases the cost of `PoseidonT3` by ~9%.
=> chore(contracts): bump poseidon-solidity version

packages/circuits/circuits/bigComparators.circom, packages/circuits/circuits/epochKeyLite.circom, packages/circuits/circuits/leafHasher.circom, packages/circuits/circuits/modulo.circom, packages/circuits/circuits/proveReputation.circom, packages/circuits/circuits/signup.circom, packages/circuits/circuits/userStateTransition.circom, packages/circuits/test/epochKeyLite.test.ts, packages/circuits/test/userStateTransition.test.ts
Closes #419 
Closes #418 
Closes #417
=> Circuit range constraints

packages/circuits/circuits/incrementalMerkleTree.circom, packages/circuits/circuits/leafHasher.circom, packages/circuits/circuits/proveReputation.circom, packages/circuits/circuits/userStateTransition.circom
Issue Number: close #420 
-
-
-
=> fix(circuits): add template variable assertions

packages/core/test/reputationProof.test.ts
issue: 
Issue Number: #312 
-
-
-
=> test(core): mirep and maxrep test

README.md, packages/circuits/README.md, packages/contracts/README.md, packages/core/README.md, packages/utils/README.md
=> doc: update package readme files

.github/pull_request_template.md
=> doc: update pull request template

packages/circuits/scripts/buildSnarks.mjs, packages/circuits/scripts/copyAtomic.mjs, packages/circuits/scripts/downloadPtau.mjs
=> fix(circuits): atomic copy build files

.circleci/config.yml
=> chore(ci): download pre-built circom in ci

packages/core/src/Synchronizer.ts
=> feat(core): register event handlers in synchronizer after constructor

packages/docs/docs/getting-started/create-unirep-app.md, packages/docs/docs/getting-started/ts-js.md
=> edit get started doc

packages/contracts/package.json, yarn.lock
=> fix(contracts): should not include `@unirep/test` in contract dependencies

.circleci/config.yml
=> chore(ci): change circom binary link

packages/circuits/src/CircuitConfig.ts, packages/contracts/contracts/Unirep.sol, packages/contracts/contracts/interfaces/IUnirep.sol, packages/contracts/deploy/deploy.ts, packages/contracts/test/config.test.ts
=> fix(contracts): change EpochKeyData layout

packages/core/src/UserState.ts, packages/core/test/synchronizerAttesters.test.ts
=> fix(core): state tree leaf computation should take `attesterId` as input

packages/core/src/Synchronizer.ts, packages/core/src/UserState.ts, packages/core/test/synchronizer.test.ts, packages/core/test/synchronizerAttesters.test.ts, packages/core/test/utils.ts, packages/docs/docs/core-api/synchronizer.md, packages/docs/docs/core-api/user-state.md
Issue Number: close #452 
-
-
-
=> feat(core): containerize the class with getters

packages/core/src/Synchronizer.ts
=> fix(core): prevent running setup twice

packages/contracts/deploy/deploy.ts, packages/contracts/test/verifier.test.ts, packages/core/test/synchronizerAttesters.test.ts, packages/docs/docs/contracts-api/epoch-key-lite-verifier-helper.md, packages/docs/docs/contracts-api/epoch-key-verifier-helper.md, packages/docs/docs/contracts-api/reputation-verifier-helper.md
=> Rm dup verifiers

packages/docs/docs/circuits-api/circuits.md, packages/docs/docs/core-api/user-state.md, packages/docs/versioned_docs/version-2.0.0-beta-3/circuits-api/circuits.md, packages/docs/versioned_docs/version-2.0.0-beta-3/core-api/user-state.md
=> doc: add warning for publishing overall reputation

packages/docs/versioned_docs/version-2.0.0-beta-3/getting-started/create-unirep-app.mdx, packages/docs/versioned_docs/version-2.0.0-beta-3/getting-started/ts-js.md, packages/docs/versioned_sidebars/version-2.0.0-beta-3-sidebars.json
- add get-started with current `create-unirep-app` version (2.0.0-beta-3)
- copy from the file in [765b8db](https://github.com/Unirep/Unirep/pull/441/commits/765b8db80cb8f5831d449645f6200a2f9de863d7)
-
=> doc: add getting started 2.0.0-beta-3

packages/docs/docs/contracts-api/unirep-sol.md, packages/docs/versioned_docs/version-2.0.0-beta-3/contracts-api/unirep-sol.md
=> doc: warn potential attestation loss

packages/docs/docs/contracts-api/unirep-sol.md
=> fix(doc): fix verifier helper path

packages/core/src/UserState.ts
Related #451 
Refactors the latest state transition logic to either successfully return or throw an error.
=> refactor(core): remove corner cases

packages/contracts/deploy/deploy.ts, packages/core/src/UserState.ts, packages/core/test/userState.test.ts, packages/docs/docs/core-api/user-state.md
=> Fix attest order

packages/circuits/circuits/bigComparators.circom, packages/circuits/circuits/userStateTransition.circom
Adds an additional constraint when splitting a value into bits.
Switches the `LessThan` comparator to a `GreaterThan` comparator during UST. New values are only taken if their nonce is `GreaterThan` the last value.
=> fix(circuits): constrain shifted bit values

packages/core/src/Synchronizer.ts, packages/core/src/schema.ts, packages/core/test/synchronizerAttesters.test.ts
- It should sync all history leaves
-
-
=> fix(core): fix handling history leaves

packages/circuits/scripts/buildSnarks.mjs, packages/circuits/src/CircuitConfig.ts
- userStateTransition
```
[INFO]  snarkJS: Curve: bn-128
[INFO]  snarkJS: # of Wires: 33801
[INFO]  snarkJS: # of Constraints: 33726
[INFO]  snarkJS: # of Private Inputs: 197
[INFO]  snarkJS: # of Public Inputs: 2
[INFO]  snarkJS: # of Labels: 103273
[INFO]  snarkJS: # of Outputs: 5
```
- epochKey
```
[INFO]  snarkJS: Curve: bn-128
[INFO]  snarkJS: # of Wires: 6304
[INFO]  snarkJS: # of Constraints: 6279
[INFO]  snarkJS: # of Private Inputs: 45
[INFO]  snarkJS: # of Public Inputs: 1
[INFO]  snarkJS: # of Labels: 19659
[INFO]  snarkJS: # of Outputs: 3
```
=> chore(circuits): update circuits config

packages/docs/docusaurus.config.js
Issue Number: close #501 
-
-
-
=> docs: add search bar

packages/docs/docs/getting-started/ts-js.md
=> doc: edit get started doc

packages/docs/docs/welcome.md, packages/docs/versioned_docs/version-2.0.0-beta-3/welcome.md
=> doc: add voteathon in welcome page

packages/core/README.md, packages/docs/docs/core-api/schema.md, packages/docs/docs/core-api/synchronizer.md, packages/docs/docs/core-api/user-state.md, packages/docs/docs/protocol/nullifiers.md
=> fix(docs): update @unirep/core documentation

packages/contracts/package.json, yarn.lock
=> fix(contracts): fix dependencies

packages/circuits/provers/web.ts, packages/docs/docs/testnet-deployment.mdx, packages/docs/versioned_docs/version-2.0.0-beta-4/testnet-deployment.mdx
=> fix(circuits): fix web prover link

packages/docs/docs/subgraph.mdx, packages/docs/sidebars.js, packages/docs/src/pages/index.js, packages/docs/src/pages/index.module.css, packages/docs/versioned_docs/version-2.0.0-beta-4/subgraph.mdx, packages/docs/versioned_sidebars/version-2.0.0-beta-4-sidebars.json
=> docs: add subgraph descriptions

packages/contracts/contracts/Unirep.sol
#529 
Issue Number: 529
- Returns the correct config value for `replFieldBits`.
=> fix: contract config returns wrong value for replFieldBits

README.md
=> doc: update PSE link and logo

packages/contracts/contracts/examples/UnirepVoting.sol, packages/contracts/contracts/examples/VotingPrizeNFT.sol, packages/contracts/test/unirepVoting.test.ts, packages/core/test/unirepVoting.test.ts
Add an example of voting with Unirep voting, the user can cast vote out of numOptions via reputation proof. 
-
-
-
=> Add UniRepVoting as an example

packages/core/src/schema.ts
- Fix schema to make it work with `IndexedDBConnector`
-
-
=> fix(core): fix schema for indexed db

packages/core/test/unirepVoting.test.ts
=> fix(core): set longer epoch length in tests

package.json, packages/circuits/README.md, packages/circuits/package.json, packages/circuits/scripts/prepare.js, packages/contracts/README.md, packages/contracts/package.json, packages/core/README.md, packages/core/package.json, packages/docs/package.json, packages/test/package.json, packages/utils/package.json
=> 2.0.0 beta 5

yarn.lock
=> fix: fix yarn lock

packages/docs/docs/testnet-deployment.mdx, packages/docs/versioned_docs/version-2.0.0-beta-5/testnet-deployment.mdx
- Polygon zkEVM doesn't support precompiled pairing
-
-
=> doc: remove zkevm deployment

packages/docs/docs/subgraph.mdx, packages/docs/versioned_docs/version-2.0.0-beta-5/subgraph.mdx
=> doc: update subgraph deployment

packages/contracts/contracts/examples/UnirepVoting.sol, packages/core/test/unirepVoting.test.ts, packages/docs/docs/contracts-api/unirep-voting-sol.md
=> doc: add unirep voting example doc

packages/core/src/schema.ts
=> fix(core): fix schema

packages/docs/docs/subgraph.mdx, packages/docs/versioned_docs/version-2.0.0-beta-4/subgraph.mdx, packages/docs/versioned_docs/version-2.0.0-beta-6/subgraph.mdx
=> fix(doc): update subgraph version

README.md, packages/contracts/package.json, packages/core/package.json
=> fix: fix install instruction, fix *.test.ts

packages/core/src/UserState.ts, packages/core/test/reputationProof.test.ts, packages/core/test/userState.test.ts
Issue Number: close #574 #573 
-
-
-
=> chore: add input range check

packages/core/src/Synchronizer.ts, packages/core/test/userStateTransition.test.ts
=> fix(core): fix query nullifiers from synchronizer

.circleci/config.yml, packages/circuits/package.json, packages/circuits/scripts/downloadKeys.sh, packages/contracts/README.md, packages/contracts/package.json, packages/core/README.md, packages/core/package.json, packages/docs/package.json, packages/subgraph/networks.json, packages/subgraph/package.json, packages/test/package.json, packages/utils/package.json, yarn.lock
=> chore: bump version and fix dependencies version

package.json, packages/circuits/package.json, yarn.lock
=> fix(circuits): fix @types/snarkjs dependency

packages/docs/versioned_docs/version-2.0.0/subgraph.mdx, packages/docs/versioned_docs/version-2.0.0/testnet-deployment.mdx, packages/subgraph/networks.json
=> doc: add supported testnet info

packages/docs/versioned_docs/version-2.0.0/subgraph.mdx, packages/docs/versioned_docs/version-2.0.0/testnet-deployment.mdx, packages/subgraph/networks.json
=> doc: add subgraph networks

packages/core/src/UserState.ts, packages/core/src/schema.ts
Issue Number: #587 
- Nullifiers should be generated from a valid epoch: where there is a state tree leaf existing
-
-
=> fix(core): fix user state to generate correct nullifiers

packages/core/src/UserState.ts
- getData epoch should not be more than `_toEpoch`
- `Epoch` schema does not have the current epoch, so I changed to use `StateTreeLeaf`
-
=> fix(core): fix get epochs

packages/core/src/Synchronizer.ts, packages/core/src/schema.ts
- fix indexed db to load double leaves
-
-
=> fix(core): fix state tree db primary key

.circleci/config.yml
=> fix: fix circle ci config for yarn
